name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          sudo apt install -y libgtk-4-dev meson ninja-build libjsonrpc-glib-1.0-dev valac
          meson _build
          ninja -C _build
